get_ensimag_logo: add missing space
Signed-off-by: Mattéo Rossillol‑‑Laruelle <beatussum@protonmail.com>

diff --git a/get_ensimag_logo b/get_ensimag_logo
--- a/get_ensimag_logo
+++ b/get_ensimag_logo
@@ -16,7 +16,7 @@ die()
 main()
 {
 	if [[ ! -d "${OUTPUT_DIR}" ]]; then
-		mkdir"${OUTPUT_DIR}" || die "Cannot create the output directory"
+		mkdir "${OUTPUT_DIR}" || die "Cannot create the output directory"
 	fi
 
 	wget \
